export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILES = "GET_PRODUCTS_FAILES";
export const GET_SINGLE_PRODUCTS_BEGIN = "GET_SINGLE_PRODUCTS_BEGIN";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAILES = "GET_SINGLE_PRODUCTS_FAILES";
